/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 *Notes:
 *	How to include header file into main.c?
 *		- Right-Click proj. > Properties > C/C++ Build Settings > Tool Settings >
 *		MCU GCC Compiler > Include paths
 *
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"

#include <stdint.h>

int main(void)
{
    return 0;
}
